// <auto-generated />
using GreekShoping.ProductApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreekShoping.ProductApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20240702194322_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GreekShoping.ProductApi.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("TbProduct");

                    b.HasData(
                        new
                        {
                            Id = 4L,
                            CategoryName = "Brinquedos",
                            Description = "Mascara para festas",
                            ImageUrl = "/prodsImages/3_vader.jpg",
                            Name = "Mascara Star Wars",
                            Price = 25000m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "Roupa",
                            Description = "Camisola de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/5_100_gamer.jpg",
                            Name = "Camisola Preta Gammer",
                            Price = 499.99m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "Roupa",
                            Description = "Camisola de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/6_spacex.jpg",
                            Name = "Camisola Branca e Preta SpaceX",
                            Price = 7500.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "Roupa",
                            Description = "Camisola de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/11_mars.jpg",
                            Name = "Camisola Preta - Occupy Mar",
                            Price = 7500.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Roupa",
                            Description = "Casaco de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/8_moletom_cobra_kay.jpg",
                            Name = "Casaco Capuchinho Preto",
                            Price = 9580m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Roupa",
                            Description = "Camisola de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/13_dragon_ball.jpg",
                            Name = "Camisola Branca - Dragon Ball Z",
                            Price = 7500.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Roupa",
                            Description = "Camisola de homem para Jovens e Adultos",
                            ImageUrl = "/prodsImages/1_super_mario.jpg",
                            Name = "Camisola - Super Mário 2000",
                            Price = 7500.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
